version: 2.1

jobs:
  test:
    docker:
      - image: sximada/python-all
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            tox

workflows:
  test:
    jobs:
      - test

